version: '3.3'
services:

  keeprice-cassandra-00:
    image: bitnami/cassandra
    ports:
    - "9042:9042"
    environment:
    - CASSANDRA_CLUSTER_NAME=keeprice-cassandra-cluster
    - CASSANDRA_SEEDS=keeprice-cassandra-00,keeprice-cassandra-01,keeprice-cassandra-02
    - CASSANDRA_PASSWORD_SEEDER=yes
    - CASSANDRA_PASSWORD=keeprice-cassandra-password

  keeprice-cassandra-01:
    image: bitnami/cassandra
    ports:
    - "9043:9042"
    environment:
    - CASSANDRA_CLUSTER_NAME=keeprice-cassandra-cluster
    - CASSANDRA_SEEDS=keeprice-cassandra-00,keeprice-cassandra-01,keeprice-cassandra-02
    - CASSANDRA_PASSWORD_SEEDER=yes
    - CASSANDRA_PASSWORD=keeprice-cassandra-password

  keeprice-cassandra-02:
    image: bitnami/cassandra
    ports:
    - "9044:9042"
    environment:
    - CASSANDRA_CLUSTER_NAME=keeprice-cassandra-cluster
    - CASSANDRA_SEEDS=keeprice-cassandra-00,keeprice-cassandra-01,keeprice-cassandra-02
    - CASSANDRA_PASSWORD_SEEDER=yes
    - CASSANDRA_PASSWORD=keeprice-cassandra-password
